# Setup
title: Satyr Farm
name:           Satyr Farm
description:    A Farming and Roleplay system for opensimulator.
logo: assets/img/satyrfarm.png
show_downloads: false
show_sidebar: true
google_analytics:


